name: GitHub Readme YouTube Cards
on:
  schedule:
    - cron: "30 14 * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          comment_tag_name: YOUTUBE-CARDS
          channel_id: ${{ secrets.YOUTUBE_CHANNEL_ID }}
