name: GitHub Readme YouTube Cards
on:
  schedule: 
    - cron: "30 14 * * TUE"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Allow the job to commit to the repository
    permissions:
      contents: write
    # Run the GitHub Readme YouTube Cards action
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: ${{ secrets.YOUTUBE_CHANNEL_ID }}
          show_duration: true
