name: GitHub Readme YouTube Cards
on:
  schedule: 
    - cron: "30 14 * * *"
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with: 
          comment_tag_name: YOUTUBE-CARDS
          youtube_api_key: ${{ secrets.YOUTUBE_CHANNEL_ID }}
          show_duration: true